# Default configuration for the CollabSphere application.
# These values can be overridden by environment variables.

server:
  port: "8010"


database:
  url: "postgres://:postgresok@localhost:5432/WithWebSocket?sslmode=disable"
  POSTGRES_HOST: "localhost"

  POSTGRES_PORT: 5432
  POSTGRES_NAME: <database name>
  POSTGRES_USER: <username login>
  POSTGRES_PASS: <password login>

jwt:
  secret: "a-very-secret-and-long-key-that-should-be-changed"

log:
  level: "debug" # Can be debug, info, warn, error
